<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<OutputPath>..\bin\$(Configuration)\</OutputPath>
		<!--<DocumentationFile>..\bin\$(Configuration)\$(TargetFramework)\SharedMemory.xml</DocumentationFile>-->
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<Company />
		<Authors>Justin Stenning</Authors>
		<Copyright>Copyright (c) 2020 Justin Stenning</Copyright>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.1'">
		<DefineConstants>NETCORE;NETCORE3_0;NET40Plus</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.0'">
		<DefineConstants>NETCORE;NETCORE2_0;NET40Plus</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(TargetFramework)' == 'net47'">
		<DefineConstants>NET45;NETFULL;NET40Plus</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(TargetFramework)' == 'net46'">
		<DefineConstants>NET45;NETFULL;NET40Plus</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(TargetFramework)' == 'net45'">
		<DefineConstants>NET45;NETFULL;NET40Plus</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(TargetFramework)' == 'net4'">
		<DefineConstants>NET40;NETFULL;NET40Plus</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(TargetFramework)' == 'net35'">
		<DefineConstants>NET35;NETFULL</DefineConstants>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
		<PackageReference Include="IndexRange" Version="1.1.1" PrivateAssets="all" />
		<PackageReference Include="System.Memory" Version="4.6.3" Private="True" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'net4' or '$(TargetFramework)' == 'net35'">
		<Compile Remove="RpcBuffer.cs" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Remove="SharedArray.cs" />
	  <Compile Remove="UnsafeNativeMethods.cs" />
	</ItemGroup>
</Project>
